### ISSUE TITLE
Number of declared basis functions seems inconsistent with the basis

### ISSUE THREAD

**Issue by wjg3** [grimme-lab/gcp#19]
See e.g. line https://github.com/grimme-lab/gcp/blob/98fcfe5b42cd62b14b5d4e73995601fe06878fba/src/gcp.f90#L1167C1-L1167C6
which states that there are 10 basis functions for Li and Be. Yet the def2-msvp has only 9 basis functions for these atoms. There is no inconsistency for these atoms in the cc-pvdz basis.

**Comment by marcelmbn** [comment]
@gasevic Relevant also for the inconsistency we've detected.

**Comment by gasevic** [comment]
You are right @wjg3. We changed the number of basis functions for Li and Be in commit 46f7044.
