### ISSUE TITLE
PBEh-3c in ORCA 6 inconsistency with stand-alone

### ISSUE THREAD

**Issue by maburs** [grimme-lab/gcp#20]
The gCP Emiss parameter for Li and the specific behavior for Kr for PBEh-3c in ORCA 6.0 differ from the stand-alone. The Nbas value used in ORCA 6.0 is correct and will be corrected in the stand-alone.

The wrong parameters are fixed for the next ORCA bugfix release.

**Comment by marcelmbn** [comment]
Thanks for your insights! Do we now have the same state in the stand-alone as in ORCA, @gasevic?

**Comment by gasevic** [comment]
This has already been fixed in commit  46f7044.
