### ISSUE TITLE
Package for conda-forge

### ISSUE THREAD

**Issue by awvwgk** [grimme-lab/gcp#4]
This project should be packaged for conda-forge at some point.

**Comment by loriab** [comment]
Is it that c-f uses an old gfortran for Windows that's the problem, and OneAPI would be a solution?

**Comment by awvwgk** [comment]
Potentially yes, Intel oneAPI compilers are working well on Linux, therefore they should work on Windows as well. Note that in meson the Intel for Windows is considered a different compiler than Intel for Unix, since the former uses a MSVS like syntax and the latter a GCC like.

An alternative for Windows is to create a MSYS2 package instead (you can actually install certain MSYS2 packages without having a MSYS2 toolchain).

**Comment by awvwgk** [comment]
The feedstock and conda package will be come shortly available under https://github.com/conda-forge/gcp-correction-feedstock.
